name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]

env:
  ECR_REPOSITORY_NAME: ecs-cluster-repo    
  ECS_SERVICE_NAME: ecs-service
  ECS_CLUSTER_NAME: ecs-cluster 
  ECS_TASK_DEFINITION_NAME: ecs-task-definition
  CONTAINER_NAME: portal

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://portal.jvictor.cloud

    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v6
      with:
        audience: sts.amazonaws.com
        aws-region: ${{ vars.AWS_REGION }}
        role-to-assume: ${{ vars.AWS_ROLE_ARN }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v4
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4
    -
      name: Build and push
      id: build-image
      uses: docker/build-push-action@v7
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      with:
        push: true
        tags: $ECR_REGISTRY/$ECR_REPOSITORY_NAME:$IMAGE_TAG

    - name: Get task definition JSON file
      id: get-task-definition-json
      env:
        ECS_TASK_DEFINITION_JSON_PATH: task-definition.json
      run: |
        echo "Generating task definition JSON file..."
        aws ecs describe-task-definition --task-definition ${{ env.ECS_TASK_DEFINITION_NAME }} \
          --query taskDefinition > ${{ env.ECS_TASK_DEFINITION_JSON_PATH }}
        echo "path=${{ env.ECS_TASK_DEFINITION_JSON_PATH }}" >> $GITHUB_OUTPUT

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ${{ steps.get-task-definition-json.outputs.path }}
        container-name: ${{ env.CONTAINER_NAME }}
        image: ${{ steps.build-image.outputs.imageid }}

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: ${{ env.ECS_SERVICE_NAME }}
        cluster: ${{ env.ECS_CLUSTER_NAME }}
        wait-for-service-stability: true
